development:
  adapter: sqlite3
  database: db/duo_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5 
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
