ruby '2.7.5'

source "https://rubygems.org"

gem 'multi_json'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end
group :test do
  gem 'rspec'
end
gem 'simplecov', require: false, group: :test
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'activerecord'
