# frozen_string_literal: true

ruby '2.7.5'

source 'https://rubygems.org'

gem 'multi_json'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end
group :test do
  gem 'factory_bot'
  gem 'faker'
  gem 'rspec'
end
gem 'activerecord'
gem 'bcrypt'
gem 'rack-test', '~> 1.1'
gem 'rake'
gem 'simplecov', require: false, group: :test
gem 'sinatra-activerecord'
gem 'sqlite3'

group :rubocop do
  gem 'rubocop', require: false
  gem 'rubocop-factory_bot', '~> 2.24'
  gem 'rubocop-rake', '~> 0.6.0'
  gem 'rubocop-rspec', '~> 2.24', '>= 2.24.1'
end
